const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Behaviors.Fade,
		C3.Behaviors.Flash,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Follow,
		C3.Behaviors.Physics,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Follow.Acts.StopFollowing,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Follow.Acts.SetDelay,
		C3.Behaviors.Follow.Acts.SetMode,
		C3.Behaviors.Follow.Acts.SetFollowingProperty,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Behaviors.Follow.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Keyboard.Cnds.OnAnyKey
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{bloco: 0},
	{fundo: 0},
	{vidalotus: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{Esmaecer: 0},
	{Piscar: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{lotus: 0},
	{colisaomorte: 0},
	{Teclado: 0},
	{bloco2: 0},
	{bloco3: 0},
	{bloco4: 0},
	{porta: 0},
	{bloco5: 0},
	{bloco6: 0},
	{fundoprompt: 0},
	{Áudio: 0},
	{primeiraFase: 0},
	{nMexe: 0},
	{MoverPara: 0},
	{Seguir: 0},
	{invi: 0},
	{emp: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{transparente: 0},
	{Sprite4: 0},
	{fundo2: 0},
	{chao: 0},
	{servidor: 0},
	{Física: 0},
	{pixilframe: 0},
	{pixilframe2: 0},
	{chao2: 0},
	{chao3: 0},
	{inimigo: 0},
	{setas: 0},
	{texto_inicializa: 0},
	{botaoplay: 0},
	{Mouse: 0},
	{fundoinicio: 0},
	{fundoti: 0},
	{titulo: 0},
	{prompt: 0},
	{fundopromptd: 0},
	{textopromt: 0},
	{textocreditos: 0},
	{vida: 0},
	{tocouintro: 0},
	{tocandomusica: 0}
];

self.InstanceType = {
	bloco: class extends self.ISpriteInstance {},
	fundo: class extends self.ISpriteInstance {},
	lotus: class extends self.ISpriteInstance {},
	colisaomorte: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	bloco2: class extends self.ISpriteInstance {},
	bloco3: class extends self.ISpriteInstance {},
	bloco4: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	bloco5: class extends self.ISpriteInstance {},
	bloco6: class extends self.ISpriteInstance {},
	fundoprompt: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	primeiraFase: class extends self.ISpriteInstance {},
	nMexe: class extends self.ISpriteInstance {},
	invi: class extends self.ISpriteInstance {},
	emp: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	transparente: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	fundo2: class extends self.ISpriteInstance {},
	chao: class extends self.ISpriteInstance {},
	servidor: class extends self.ISpriteInstance {},
	pixilframe: class extends self.ISpriteInstance {},
	pixilframe2: class extends self.ISpriteInstance {},
	chao2: class extends self.ISpriteInstance {},
	chao3: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	setas: class extends self.ISpriteInstance {},
	texto_inicializa: class extends self.ISpriteInstance {},
	botaoplay: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	fundoinicio: class extends self.ISpriteInstance {},
	fundoti: class extends self.ISpriteInstance {},
	titulo: class extends self.ISpriteInstance {},
	prompt: class extends self.ISpriteInstance {},
	fundopromptd: class extends self.ISpriteInstance {},
	textopromt: class extends self.ISpriteInstance {},
	textocreditos: class extends self.ISpriteInstance {}
}